// Content descriptions - movie/show titles stay in English (not translated)
// Keys: contentId -> { d: short description, l: long description }
// Languages without full data fall back to English

const CONTENT_TRANSLATIONS = {
  en: {
    1: { d: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl. A love letter to the '80s supernatural classics.", l: "It's the fall of 1983 in Hawkins, Indiana. After the mysterious disappearance of young Will Byers, his friends and family embark on an extraordinary journey to find him. They soon discover a secret government lab, a sinister supernatural force, and a peculiar girl with psychokinetic abilities. As they uncover the truth, they must save Hawkins from a monster that has escaped from an alternate dimension." },
    2: { d: "A high school chemistry teacher diagnosed with cancer turns to manufacturing and selling methamphetamine to secure his family's future.", l: "Walter White, a meek high school chemistry teacher, learns he has terminal cancer. To provide for his family, he teams up with former student Jesse Pinkman to manufacture and sell crystal meth. As Walter descends deeper into the criminal underworld, he transforms from a desperate man into a ruthless drug lord known as Heisenberg." },
    3: { d: "The reign of Queen Elizabeth II and the events that shaped the second half of the 20th century and beyond.", l: "This acclaimed drama follows the reign of Queen Elizabeth II from the 1940s to modern times. Beginning with her marriage to Philip, Duke of Edinburgh, the series chronicles the Queen's relationship with prime ministers, the Suez Crisis, the Aberfan disaster, the assassination attempt on Margaret Thatcher, and the breakdown of her children's marriages." },
    4: { d: "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a killing spree at her school while navigating her new psychic abilities.", l: "Wednesday Addams is sent to Nevermore Academy, a school for outcasts. When a monstrous killer terrorizes the town, she attempts to master her emerging psychic ability to stop it. Along the way, she must navigate her complicated relationships and uncover a family secret that dates back decades." },
    5: { d: "A financial adviser drags his family from Chicago to the Missouri Ozarks, where he must launder $500 million to appease a drug cartel.", l: "Marty Byrde, a financial planner, relocates his family from Chicago to a summer resort community in the Ozarks after a money-laundering scheme goes wrong. He must now launder $500 million in five years to appease a Mexican drug cartel, while navigating dangerous alliances and keeping his family safe." },
    6: { d: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits—with deadly high stakes.", l: "456 desperate contestants who are deeply in debt risk their lives to play a series of deadly children's games for a chance to win 45.6 billion won. The games are a brutal survival competition with eliminations, testing the limits of human nature, loyalty, and greed." },
    7: { d: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.", l: "The Witcher follows Geralt of Rivia, a mutated monster hunter for hire, as he journeys toward his destiny in a turbulent world where people often prove more wicked than beasts. Based on the best-selling fantasy series of books." },
    8: { d: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history—stealing 2.4 billion euros from the Royal Mint of Spain.", l: "Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan. Dressed in red jumpsuits and Salvador Dalí masks, the robbers become worldwide sensations." },
    9: { d: "In a 1950s orphanage, a young girl reveals an astonishing talent for chess and begins an unlikely journey to stardom while grappling with addiction.", l: "Orphaned at 9, Beth Harmon is sent to an orphanage where she discovers her prodigious talent for chess. As she rises to compete in the male-dominated world of competitive chess in the 1960s, she struggles with drug and alcohol dependency while battling her inner demons." },
    10: { d: "The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society.", l: "Wealthy, powerful and privileged, the Bridgertons are a close-knit family navigating the competitive marriage market in Regency London. The series follows the eight siblings as they seek love and happiness amid scandal, intrigue, and ballroom gossip." },
    11: { d: "Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.", l: "Assane Diop's life was shattered when his father died after being accused of a crime he didn't commit. 25 years later, Assane uses the character of gentleman thief Arsène Lupin to carry out an elaborate plan of revenge against the wealthy Pellegrini family." },
    12: { d: "A missing child sets four families on a frantic hunt for answers as they uncover a mind-bending mystery that spans three generations.", l: "When two children go missing in a small German town, its sinful past is exposed along with the double lives and fractured relationships that exist among four families as they search for the kids. The mystery stretches across three generations of families." },
    13: { d: "A gangster family epic set in 1919 Birmingham, England, centered on a gang who sew razor blades in the peaks of their caps.", l: "Thomas Shelby and his brothers return to Birmingham after serving in WWI. The Shelby family controls the city's illegal betting operations, but Thomas has ambitions beyond the narrow confines of his local power. His meteoric rise brings him into contact with both royal family and common criminals." },
    14: { d: "An anthology series exploring a twisted, high-tech world where humanity's greatest innovations and darkest instincts collide.", l: "This sci-fi anthology series explores a multiverse of possibilities—where technological advances lead to disturbing consequences. Each standalone episode examines modern society through the lens of speculative fiction, revealing how technology can reflect and amplify our worst tendencies." },
    15: { d: "A woman with mysterious abilities reappears after having been missing for seven years. Her return sets off an intricate mystery.", l: "After seven years missing, Prairie Johnson returns home blind but with her sight restored. She refuses to tell the FBI or her adoptive parents where she's been, but privately shares her story with a group of local residents. She calls herself The OA and reveals she was held captive by a scientist conducting experiments on near-death experiences." },
    16: { d: "After their father's murder, three siblings move into a house filled with magical keys that may be connected to their father's death.", l: "After Rendell Locke's murder, his widow Nina moves her family to his ancestral estate in Massachusetts. The Locke children discover magical keys throughout the house that give them powers. They soon find they're not the only ones interested in the keys, as a demonic entity wants them for its own purposes." },
    17: { d: "A family of former child heroes, now grown apart, must reunite to protect the world from a threat—and each other.", l: "On one day in 1989, 43 infants were born to mothers who had shown no signs of pregnancy. Seven are adopted by a billionaire who creates The Umbrella Academy to prepare them to save the world. Now the estranged siblings must reunite when they learn of their father's death and an impending apocalypse." },
    18: { d: "A Navy SEAL investigates why his entire platoon was ambushed during a high-stakes covert mission.", l: "Lieutenant Commander James Reece returns home to his family after his entire platoon of Navy SEALs is ambushed during a high-stakes covert mission. As he processes the memories of the fatal mission, Reece discovers dark forces working against him, threatening not just his life but the lives of those he loves." },
    19: { d: "When CIA analyst Jack Ryan stumbles upon a suspicious pattern of terrorist transfers, he uncovers a plan to attack the U.S.", l: "Jack Ryan, an up-and-coming CIA analyst, is thrust into a dangerous field assignment for the first time. He uncovers a pattern in terrorist communication that launches him into the center of a dangerous gambit with a new breed of terrorism that threatens to disrupt the globe." },
    20: { d: "As Alfred the Great defends his kingdom from Norse invaders, Uhtred—born a Saxon but raised by Vikings—seeks to claim his ancestral birthright.", l: "In the late 9th century, the Kingdom of Wessex is the last English stronghold against Danish Vikings. Uhtred, born a Saxon noble but raised by Vikings, is torn between his two peoples. He must choose a side and use his warrior skills to help Alfred the Great defend Wessex and ultimately claim his ancestral land." },
    21: { d: "Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Viking warrior and farmer who yearns to explore.", l: "The series follows the adventures of Ragnar Lothbrok, a Viking farmer and warrior who ascends to become a legendary Viking leader. From the first raids on England to the exploration of uncharted territories, Ragnar and his family face battles, betrayals, and the clash of cultures as they forge a new world." },
    22: { d: "Harvard student Mark Zuckerberg creates a social networking site that would become Facebook.", l: "In 2003, Harvard undergrad Mark Zuckerberg creates a social networking site from his dorm room. Six years and 500 million friends later, he becomes the youngest billionaire in history—but discovers that wealth and success come with both personal and legal complications." },
    23: { d: "A thief who steals corporate secrets through dream-sharing technology is offered a chance to have his criminal record expunged.", l: "Dom Cobb is a skilled thief who extracts secrets from the subconscious during dreams. He's offered a chance to have his criminal record erased if he can successfully perform inception—planting an idea in someone's mind—a task considered impossible." },
    24: { d: "A noble family becomes embroiled in a war for control of the galaxy's most valuable asset.", l: "Paul Atreides leads his family to the dangerous planet Arrakis to steward its supply of melange, the most precious resource in the universe. As evil forces explode into conflict over the planet and its spice, only those who can conquer their fear will survive." },
    25: { d: "After thirty years, Maverick is still pushing the envelope as a top naval aviator.", l: "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell must confront his past when he trains a squadron of graduates for a dangerous mission." },
    26: { d: "The origins of two legendary League of Legends champions—sisters Vi and Jinx—and the power that will tear them apart.", l: "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and conflicting beliefs. The series explores the thin line between heroes and villains." },
    27: { d: "The story of the rise and fall of Pablo Escobar and the Drug Enforcement Agency.", l: "The true story of Colombia's infamously violent and powerful drug cartels fuels this gritty crime saga. The series chronicles the rise of the cocaine trade in Colombia and the real-life characters behind it." },
    28: { d: "When the Sandman, Lord of Dreams, is captured, he must journey across worlds to fix the chaos his absence has caused.", l: "After years of imprisonment, Dream escapes and sets out to restore his kingdom. He must retrieve his tools of power, travel through different worlds and timelines to fix the mistakes he's made." },
    29: { d: "A family moves into their dream home, only to be threatened by terrifying letters from a stalker.", l: "The Brannocks move into their dream home in suburban New Jersey. They soon receive alarming letters from someone calling themselves 'The Watcher' who is watching their every move." },
    30: { d: "A young German soldier's terrifying experiences during World War I.", l: "Paul and his comrades experience the horrors of the First World War in the trenches of the Western Front. They fight for survival in a war that seems to have no end." },
    31: { d: "A low-level FBI agent works in the basement of the White House, manning a phone that never rings—until it does.", l: "When that phone finally rings, he's thrust into a conspiracy that leads to the highest levels of government. He must uncover the truth while protecting a civilian tech worker being hunted by assassins." },
    32: { d: "A hardened mercenary's mission becomes a soul-searing race to survive when he's sent to Bangladesh to rescue a drug lord's kidnapped son.", l: "Tyler Rake, a fearless black market mercenary, embarks on the deadliest mission of his career when he's hired to rescue the kidnapped son of an imprisoned international crime lord." },
    33: { d: "Tech billionaire Miles Bron invites his friends to a private island for a murder mystery party.", l: "Detective Benoit Blanc travels to a private Greek island to join a gathering of friends, where one of them will be murdered. The mystery deepens as secrets are uncovered." },
    34: { d: "When the CIA's most skilled operative uncovers agency secrets, a psychopathic former colleague puts a bounty on his head.", l: "Court Gentry, aka Sierra Six, is the CIA's most skilled mercenary. When he uncovers dark agency secrets, a psychopathic former colleague puts a bounty on his head, setting off a global manhunt." },
    35: { d: "In the late 1970s, two FBI agents expand criminal science by delving into the psychology of murder.", l: "FBI agents Holden Ford and Bill Tench interview imprisoned serial killers to understand how they think and apply those insights to solve open cases. Their revolutionary research leads them to dangerous conclusions." },
    36: { d: "A road rage incident between two strangers leads to an escalating feud.", l: "A road rage incident between a contractor and an entrepreneur spirals into a dark journey of revenge and shared trauma. Their feud reveals deeper issues lurking beneath the surface." },
    37: { d: "In the midst of an international crisis, a diplomat is offered a job she's not sure she wants.", l: "Kate Wyler is a career diplomat who lands in a high-stakes job she never wanted. She must defuse international crises, manage her marriage, and navigate the halls of power." },
    38: { d: "A detective investigates the death of a wealthy patriarch of an eccentric family.", l: "When renowned crime novelist Harlan Thrombey is found dead, detective Benoit Blanc is hired to investigate. He sifts through a web of lies and red herrings to uncover the truth." },
  },
  es: {
    1: { d: "Cuando un niño desaparece, un pequeño pueblo descubre un misterio que involucra experimentos secretos, fuerzas sobrenaturales aterradoras y una extraña niña. Una carta de amor a los clásicos sobrenaturales de los 80.", l: "Es otoño de 1983 en Hawkins, Indiana. Tras la misteriosa desaparición del pequeño Will Byers, sus amigos y familia emprenden un viaje extraordinario para encontrarlo. Pronto descubren un laboratorio gubernamental secreto, una siniestra fuerza sobrenatural y una peculiar niña con habilidades psicokinéticas. Al descubrir la verdad, deben salvar Hawkins de un monstruo escapado de una dimensión alterna." },
    2: { d: "Un profesor de química con cáncer se dedica a fabricar y vender metanfetamina para asegurar el futuro de su familia.", l: "Walter White, un tímido profesor de química, descubre que tiene cáncer terminal. Para mantener a su familia, se asocia con un ex alumno, Jesse Pinkman, para fabricar metanfetamina. A medida que Walter desciende en el inframundo criminal, se transforma de un hombre desesperado en un despiadado narcotraficante conocido como Heisenberg." },
    3: { d: "El reinado de la reina Isabel II y los acontecimientos que marcaron la segunda mitad del siglo XX y más allá.", l: "Este aclamado drama sigue el reinado de la reina Isabel II desde los años 40 hasta la actualidad. Desde su matrimonio con Felipe, duque de Edimburgo, la serie relata la relación de la reina con los primeros ministros, la crisis de Suez, la tragedia de Aberfan, el intento de asesinato de Margaret Thatcher y la ruptura de los matrimonios de sus hijos." },
    4: { d: "Inteligente, sarcástica y un poco muerta por dentro, Wednesday Addams investiga una ola de asesinatos en su escuela mientras descubre sus nuevas habilidades psíquicas.", l: "Wednesday Addams es enviada a la Academia Nevermore, una escuela para inadaptados. Cuando un asesino monstruoso aterra el pueblo, intenta dominar su naciente habilidad psíquica para detenerlo. En el camino, debe navegar sus complicadas relaciones y descubrir un secreto familiar que data de décadas." },
    5: { d: "Un asesor financiero traslada a su familia de Chicago a los Ozarks de Missouri, donde debe lavar 500 millones de dólares para satisfacer a un cártel de drogas.", l: "Marty Byrde, planificador financiero, traslada a su familia de Chicago a una comunidad turística en los Ozarks tras un fallido esquema de lavado de dinero. Debe lavar 500 millones de dólares en cinco años para satisfacer a un cártel mexicano, mientras navega alianzas peligrosas y mantiene a salvo a su familia." },
  },
  fr: {
    1: { d: "Quand un jeune garçon disparaît, une petite ville découvre un mystère impliquant des expériences secrètes, des forces surnaturelles terrifiantes et une étrange petite fille. Une lettre d'amour aux classiques surnaturels des années 80.", l: "C'est l'automne 1983 à Hawkins, Indiana. Après la disparition mystérieuse du jeune Will Byers, ses amis et sa famille se lancent dans un voyage extraordinaire pour le retrouver. Ils découvrent bientôt un laboratoire gouvernemental secret, une sinistre force surnaturelle et une fille particulière aux capacités psychokinétiques. En découvrant la vérité, ils doivent sauver Hawkins d'un monstre échappé d'une dimension alternative." },
    2: { d: "Un professeur de chimie atteint d'un cancer se lance dans la fabrication et la vente de méthamphétamine pour assurer l'avenir de sa famille.", l: "Walter White, un modeste professeur de chimie, apprend qu'il a un cancer en phase terminale. Pour subvenir aux besoins de sa famille, il s'associe à un ancien élève, Jesse Pinkman, pour fabriquer et vendre de la méthamphétamine. Alors qu'il s'enfonce dans le milieu criminel, Walter se transforme d'un homme désespéré en un impitoyable baron de la drogue connu sous le nom d'Heisenberg." },
    3: { d: "Le règne de la reine Elizabeth II et les événements qui ont façonné la seconde moitié du XXe siècle et au-delà.", l: "Ce drame acclamé suit le règne de la reine Elizabeth II des années 40 à nos jours. À partir de son mariage avec Philip, duc d'Édimbourg, la série relate la relation de la reine avec les premiers ministres, la crise de Suez, la tragédie d'Aberfan, la tentative d'assassinat de Margaret Thatcher et l'effondrement des mariages de ses enfants." },
    4: { d: "Intelligente, sarcastique et un peu morte intérieurement, Wednesday Addams enquête sur une série de meurtres dans son école tout en découvrant ses nouvelles capacités psychiques.", l: "Wednesday Addams est envoyée à l'Académie Nevermore, une école pour marginaux. Quand un tueur monstrueux terrorise la ville, elle tente de maîtriser son émergente capacité psychique pour l'arrêter. En chemin, elle doit naviguer dans ses relations compliquées et découvrir un secret familial qui date de décennies." },
    5: { d: "Un conseiller financier emmène sa famille de Chicago dans les Ozarks du Missouri, où il doit blanchir 500 millions de dollars pour satisfaire un cartel de drogue.", l: "Marty Byrde, un planificateur financier, déménage sa famille de Chicago dans une station estivale des Ozarks après l'échec d'un schéma de blanchiment. Il doit maintenant blanchir 500 millions de dollars en cinq ans pour satisfaire un cartel mexicain, tout en naviguant des alliances dangereuses et en protégeant sa famille." },
  },
  de: {
    1: { d: "Als ein junger Junge verschwindet, deckt eine Kleinstadt ein Geheimnis auf, das geheime Experimente, furchterregende übernatürliche Kräfte und ein seltsames kleines Mädchen umfasst. Ein Liebesbrief an die Übernatürlichkeitsklassiker der 80er.", l: "Es ist Herbst 1983 in Hawkins, Indiana. Nach dem geheimnisvollen Verschwinden des jungen Will Byers begeben sich seine Freunde und Familie auf eine außergewöhnliche Reise, um ihn zu finden. Sie entdecken bald ein geheimes Regierungslabor, eine unheimliche übernatürliche Kraft und ein merkwürdiges Mädchen mit psychokinetischen Fähigkeiten. Beim Aufdecken der Wahrheit müssen sie Hawkins vor einem Monster retten, das aus einer anderen Dimension entkommen ist." },
    2: { d: "Ein Chemielehrer mit Krebsverdacht wendet sich der Herstellung und dem Verkauf von Methamphetamin zu, um die Zukunft seiner Familie zu sichern.", l: "Walter White, ein sanftmütiger Chemielehrer, erfährt, dass er unheilbar an Krebs erkrankt ist. Um seine Familie zu versorgen, verbündet er sich mit seinem ehemaligen Schüler Jesse Pinkman, um Crystal Meth herzustellen und zu verkaufen. Als Walter tiefer in die kriminelle Unterwelt absteigt, verwandelt er sich von einem verzweifelten Mann in einen skrupellosen Drogenbaron namens Heisenberg." },
    3: { d: "Die Regierungszeit von Königin Elizabeth II. und die Ereignisse, die die zweite Hälfte des 20. Jahrhunderts und darüber hinaus prägten.", l: "Diese gefeierte Serie folgt der Regierungszeit von Königin Elizabeth II. von den 1940ern bis in die Neuzeit. Beginnend mit ihrer Heirat mit Philip, Herzog von Edinburgh, thematisiert die Serie die Beziehung der Königin zu Premierministern, die Sueskrise, die Aberfan-Katastrophe, das Attentat auf Margaret Thatcher und den Zusammenbruch der Ehen ihrer Kinder." },
    4: { d: "Schlau, sarkastisch und ein bisschen tot von innen, Wednesday Addams ermittelt bei einer Mordserie an ihrer Schule und entdeckt dabei ihre neuen psychischen Fähigkeiten.", l: "Wednesday Addams wird auf die Nevermore Academy geschickt, eine Schule für Außenseiter. Als ein monströser Killer die Stadt terrorisiert, versucht sie, ihre aufkeimende psychische Fähigkeit zu meistern, um ihn zu stoppen. Unterwegs muss sie ihre komplizierten Beziehungen navigieren und ein Familiengeheimnis aufdecken, das Jahrzehnte zurückreicht." },
    5: { d: "Ein Finanzberater zieht seine Familie von Chicago in die Ozarks von Missouri, wo er 500 Millionen Dollar waschen muss, um ein Drogenkartell zu besänftigen.", l: "Marty Byrde, ein Finanzplaner, verlegt seine Familie von Chicago in eine Feriencommunity in den Ozarks nach einem gescheiterten Geldwäscheschema. Er muss jetzt 500 Millionen Dollar in fünf Jahren waschen, um ein mexikanisches Drogenkartell zu besänftigen, während er gefährliche Allianzen navigiert und seine Familie in Sicherheit hält." },
  },
  it: {
    1: { d: "Quando un bambino scompare, ​​una piccola città scopre un mistero che coinvolge esperimenti segreti, terrificanti forze soprannaturali e una strana bambina. Una lettera d'amore ai classici soprannaturali degli anni '80.", l: "È l'autunno del 1983 a Hawkins, Indiana. Dopo la misteriosa scomparsa del piccolo Will Byers, amici e famiglia intraprendono un viaggio straordinario per trovarlo. Scoprono presto un laboratorio governativo segreto, una sinistra forza soprannaturale e una ragazzina con capacità psicocinetiche. Scoprendo la verità, dovranno salvare Hawkins da un mostro fuggito da una dimensione alternativa." },
    3: { d: "Il regno della regina Elisabetta II e gli eventi che hanno plasmato la seconda metà del XX secolo e oltre.", l: "Questo acclamato dramma segue il regno della regina Elisabetta II dagli anni '40 a oggi. Dal matrimonio con Filippo, duca di Edinburgh, la serie racconta i rapporti della Regina con i primi ministri, la crisi di Suez, la tragedia di Aberfan, l'attentato a Margaret Thatcher e la crisi dei matrimoni dei figli." },
    4: { d: "Intelligente, sarcastica e un po' morta dentro, Wednesday Addams indaga su una serie di omicidi nella sua scuola mentre scopre i suoi nuovi poteri psichici.", l: "Wednesday Addams viene mandata alla Nevermore Academy, una scuola per emarginati. Quando un killer mostruoso terrorizza la città, cerca di padroneggiare il suo nascente potere psichico per fermarlo. Lungo la strada deve affrontare le sue complicate relazioni e scoprire un segreto di famiglia che risale a decenni." },
  },
  pt: {
    1: { d: "Quando um menino desaparece, uma pequena cidade descobre um mistério envolvendo experimentos secretos, forças sobrenaturais aterradoras e uma estranha menininha. Uma carta de amor aos clássicos sobrenaturais dos anos 80.", l: "É outono de 1983 em Hawkins, Indiana. Após o misterioso desaparecimento do jovem Will Byers, amigos e família embarcam numa jornada extraordinária para encontrá-lo. Logo descobrem um laboratório governamental secreto, uma força sobrenatural sinistra e uma menina peculiar com habilidades psicocinéticas. Ao descobrirem a verdade, precisam salvar Hawkins de um monstro que escapou de outra dimensão." },
    3: { d: "O reinado da rainha Elizabeth II e os eventos que moldaram a segunda metade do século XX e além.", l: "Este aclamado drama acompanha o reinado da rainha Elizabeth II dos anos 40 aos dias atuais. A partir do casamento com Filipe, duque de Edimburgo, a série relata a relação da rainha com os primeiros-ministros, a crise de Suez, a tragédia de Aberfan, o atentado a Margaret Thatcher e a ruptura dos casamentos dos filhos." },
    4: { d: "Inteligente, sarcástica e um pouco morta por dentro, Wednesday Addams investiga uma série de assassinatos na escola enquanto descobre suas novas habilidades psíquicas.", l: "Wednesday Addams é enviada à Academia Nevermore, uma escola para desajustados. Quando um assassino monstruoso aterroriza a cidade, ela tenta dominar sua nascente habilidade psíquica para detê-lo. No caminho, precisa lidar com seus relacionamentos complicados e descobrir um segredo de família que remonta a décadas." },
  },
  ja: {
    1: { d: "少年が忽然と消えたとき、小さな町は秘密実験、恐ろしい超自然的な力、奇妙な少女をめぐる謎に巻き込まれる。80年代超自然クラシックへのラブレター。", l: "1983年の秋、インディアナ州ホーキンス。少年ウィル・バイヤーズの謎の失踪後、友人と家族は彼を探す壮大な旅に乗り出す。やがて秘密の政府研究所、不気味な超自然的な力、念動力を持つ不思議な少女を発見する。真実を暴き、異次元から逃げてきた怪物からホーキンスを救わなければならない。" },
    3: { d: "エリザベス2世の治世と20世紀後半を形づくった出来事。", l: "この名作ドラマは1940年代から現代までのエリザベス2世の治世を描く。エディンバラ公フィリップとの結婚から始まり、女王と首相たちとの関係、スエズ危機、アベルファン悲劇、マーガレット・サッチャー暗殺未遂、子供たちの結婚の崩壊までを描く。" },
    4: { d: "聡明で皮肉的、心は少し死んでいるウェンズデー・アダムズが、新たな超能力を駆使しながら学校で起きた連続殺人を調査する。", l: "ウェンズデー・アダムズは、落ちこぼれのための学校ネバーモア・アカデミーに送られる。怪物のような殺人鬼が町を恐怖に陥れたとき、彼女は現れつつある超能力をマスターして阻止しようとする。複雑な人間関係を乗り越え、数十年にさかのぼる家族の秘密を解き明かすことになる。" },
  },
  ko: {
    1: { d: "소년이 사라지자 작은 마을이 비밀 실험, 끔찍한 초자연적 힘, 그리고 이상한 소녀를 둘러싼 미스터리를 발견한다. 80년대 초자연 클래식에 대한 감사 편지.", l: "1983년 가을, 인디애나주 호킨스. 어린 윌 바이어스가 신비롭게 사라진 후 친구와 가족은 그를 찾기 위한 특별한 여정에 나선다. 곧 비밀 정부 연구소, 불길한 초자연적 힘, 염력 능력을 가진 특이한 소녀를 발견한다. 진실을 밝히며 대체 차원에서 도망친 괴물로부터 호킨스를 구해야 한다." },
    3: { d: "엘리자베스 2세의 통치와 20세기 후반을 형성한 사건들.", l: "이 호평받는 드라마는 1940년대부터 현대까지 엘리자베스 2세의 통치를 따른다. 에든버러 공작 필립과의 결혼을 시작으로, 수에즈 위기, 애버판 참사, 마거릿 대처 암살 미수, 자녀들의 결혼 파탄 등 여왕의 이야기를 그린다." },
    4: { d: "영리하고 냉소적이며 내면이 조금 죽은 웬즈데이 애덤스가 학교 연쇄 살인을 조사하며 새로운 심령 능력을 탐색한다.", l: "웬즈데이 애덤스는 낙오자들을 위한 학교 네버모어 아카데미로 보내진다. 괴물 같은 살인마가 마을을 공포에 빠뜨리자, 그를 막기 위해 떠오르는 심령 능력을 마스터하려 한다. 그 과정에서 복잡한 관계를 헤쳐 나가고 수십 년 전의 가족 비밀을 밝혀야 한다." },
  },
  zh: {
    1: { d: "当一个男孩突然消失，小镇揭开了一个涉及秘密实验、恐怖超自然力量和神秘女孩的谜团。献给80年代超自然经典的情书。", l: "1983年秋天，印第安纳州霍金斯。年轻威尔·拜尔斯神秘失踪后，他的朋友和家人踏上了寻找他的非凡旅程。他们很快发现了一个秘密政府实验室、邪恶的超自然力量和一个拥有心灵感应能力的奇特女孩。在揭露真相的同时，他们必须从另一个维度逃脱的怪物手中拯救霍金斯。" },
    3: { d: "伊丽莎白二世女王的统治以及塑造20世纪下半叶及以后的事件。", l: "这部广受好评的剧集追溯了伊丽莎白二世女王从1940年代到现代的统治。从她与爱丁堡公爵菲利普的婚姻开始，系列剧讲述了女王与首相的关系、苏伊士危机、阿伯凡灾难、针对撒切尔夫人的暗杀未遂以及子女婚姻的破裂。" },
    4: { d: "聪明、讽刺、内心有些麻木的星期三·亚当斯在学校调查连环杀人案的同时探索着她新的超能力。", l: "星期三·亚当斯被送到异类学校Nevermore Academy。当怪物般的杀手肆虐小镇时，她试图掌握自己正在觉醒的心灵感应能力来阻止他。一路上，她必须应对复杂的人际关系，揭开一个可追溯至数十年前的家庭秘密。" },
  },
  ar: {
    1: { d: "عندما يختفي صبي صغير، تكشف بلدة صغيرة عن لغز يتضمن تجارب سرية وقوى خارقة مخيفة وفتاة غريبة. رسالة حب لأعمال الخوارق الكلاسيكية في الثمانينيات.", l: "خريف 1983 في هوكينز، إنديانا. بعد اختفاء ويل بايرز الغامض، يشرع أصدقاؤه وعائلته في رحلة استثنائية للعثور عليه. يكتشفون قريباً مختبراً حكومياً سرياً وقوة خارقة شريرة وفتاة غريبة ذات قدرات تحريك الأشياء. وعند كشف الحقيقة، يجب عليهم إنقاذ هوكينز من وحش هارب من بُعد بديل." },
    3: { d: "عهد الملكة إليزابيث الثانية والأحداث التي شكلت النصف الثاني من القرن العشرين وما بعده.", l: "تتبع هذه الدراما المُشاد بها عهد الملكة إليزابيث الثانية من الأربعينيات حتى العصر الحديث. بدءاً بزواجها من فيليب دوق إدنبرة، تسرد المسلسل علاقة الملكة برؤساء الوزراء وأزمة السويس ومأساة أبرفان ومحاولة اغتيال مارغريت ثاتشر وانهيار زيجات أبنائها." },
    4: { d: "ذكية وساخرة وميتة قليلاً من الداخل، Wednesday Addams تحقق في سلسلة جرائم قتل في مدرستها بينما تكتشف قدراتها النفسية الجديدة.", l: "تُرسل Wednesday Addams إلى أكاديمية Nevermore، مدرسة للمنبوذين. عندما يرعب قاتل وحشي المدينة، تحاول إتقان قدرتها النفسية الناشئة لإيقافه. في الطريق عليها التعامل مع علاقاتها المعقدة وكشف سر عائلي يعود لعقود." },
  },
  he: {
    1: { d: "כשילד צעיר נעלם, עיירה קטנה מגלה תעלומה שכוללת ניסויים סודיים, כוחות על־טבעיים מפחידים וילדה מוזרה. מכתב אהבה לקלאסיקות העל־טבעיות של שנות השמונים.", l: "סתיו 1983 בהוקינס, אינדיאנה. אחרי היעלמותו המסתורית של ויל ביירס הצעיר, חבריו ומשפחתו יוצאים למסע יוצא דופן למצוא אותו. הם מגלים עד מהרה מעבדה ממשלתית סודית, כוח על־טבעי מפחיד וילדה מוזרה עם יכולות פסיכוקינטיות. בחושפם את האמת, עליהם להציל את הוקינס ממפלצת שברחה מממד אחר." },
    3: { d: "תקופת שלטונה של המלכה אליזבת השנייה והאירועים שעצבו את מחצית המאה העשרים ומעבר לה.", l: "הדרמה המהוללת הזו עוקבת אחר תקופת שלטונה של המלכה אליזבת השנייה משנות ה־40 עד ימינו. החל בנישואיה לפיליפ, דוכס אדינבורו, הסדרה מתעדת את יחסי המלכה עם ראשי ממשלה, משבר סואץ, טרגדיית אַבֶּרפָאן, ניסיון ההתנקשות במרגרט ת'אצ'ר והתפוררות נישואי ילדיה." },
    4: { d: "חכמה, סרקסטית ומעט מתה מבפנים, Wednesday Addams חוקרת גל רציחות בבית ספרה בעודה מגלה את יכולותיה הפסיכיות החדשות.", l: "Wednesday Addams נשלחת לאקדמיית Nevermore, בית ספר לדחויים. כשרוצח מפלצתי מפיל אימה על העיר, היא מנסה לשלוט ביכולת הפסיכית המתפתחת שלה כדי לעצור אותו. בדרך עליה לנווט את מערכות היחסים המורכבות שלה ולגלות סוד משפחתי שמגיע עשרות שנים אחורה." },
  },
  tr: { 1: { d: "Küçük bir çocuk kaybolduğunda, bir kasaba gizli deneyler, korkunç doğaüstü güçler ve tuhaf bir kızı içeren bir gizemi ortaya çıkarır. 80'lerin doğaüstü klasiklerine bir aşk mektubu.", l: "" }, 3: { d: "Kraliçe II. Elizabeth'in saltanatı ve 20. yüzyılın ikinci yarısını ve ötesini şekillendiren olaylar.", l: "" }, 4: { d: "Zeki, alaycı ve içten içe biraz ölü Wednesday Addams, yeni psişik yeteneklerini keşfederken okulunda bir cinayet serisini araştırır.", l: "" } },
  pl: { 1: { d: "Gdy znika młody chłopiec, małe miasto odkrywa tajemnicę związaną z tajnymi eksperymentami, przerażającymi siłami nadprzyrodzonymi i dziwną dziewczynką. List miłosny do nadprzyrodzonych klasyków lat 80.", l: "" }, 3: { d: "Panowanie królowej Elżbiety II i wydarzenia kształtujące drugą połowę XX wieku i dalej.", l: "" }, 4: { d: "Bystra, sarkastyczna i trochę martwa w środku Wednesday Addams bada serię morderstw w szkole, odkrywając swoje nowe zdolności psychiczne.", l: "" } },
  nl: { 1: { d: "Wanneer een jongen verdwijnt, ontdekt een klein stadje een mysterie met geheime experimenten, angstaanjagende bovennatuurlijke krachten en een vreemd meisje. Een liefdesbrief aan de bovennatuurlijke klassiekers van de jaren 80.", l: "" }, 3: { d: "De regering van koningin Elizabeth II en de gebeurtenissen die de tweede helft van de 20e eeuw en daarna vorm gaven.", l: "" }, 4: { d: "Slim, sarkastisch en een beetje dood vanbinnen, Wednesday Addams onderzoekt een reeks moorden op haar school terwijl ze haar nieuwe paragnostische gaven ontdekt.", l: "" } },
  ru: { 1: { d: "Когда исчезает мальчик, маленький городок раскрывает тайну тайных экспериментов, ужасных сверхъестественных сил и странной девочки. Письмо любви к сверхъестественным классикам 80-х.", l: "" }, 3: { d: "Правление королевы Елизаветы II и события, сформировавшие вторую половину XX века и далее.", l: "" }, 4: { d: "Умная, саркастичная и немного мёртвая внутри Wednesday Addams расследует серию убийств в школе, открывая свои новые психические способности.", l: "" } },
  th: { 1: { d: "เมื่อเด็กชายหายไป เมืองเล็กๆ เปิดเผยความลึกลับเกี่ยวกับการทดลองลับ แรงอำนาจเหนือธรรมชาติที่น่าหวาดกลัว และเด็กหญิงแปลกประหลาด บทกวีรักแด่คลาสสิกเหนือธรรมชาติยุค 80", l: "" }, 3: { d: "รัชสมัยของสมเด็จพระราชินีเอลิซาเบธที่ 2 และเหตุการณ์ที่หล่อหลอมครึ่งหลังของศตวรรษที่ 20 และต่อเนื่อง", l: "" }, 4: { d: "ฉลาด เสียดสี และตายด้านในเล็กน้อย Wednesday Addams สืบสวนคดีฆาตกรรมต่อเนื่องที่โรงเรียน ขณะค้นพบความสามารถทางจิตใหม่ของเธอ", l: "" } },
  vi: { 1: { d: "Khi một cậu bé biến mất, thị trấn nhỏ phát hiện bí ẩn liên quan đến thí nghiệm bí mật, thế lực siêu nhiên đáng sợ và cô gái kỳ lạ. Bức thư tình gửi các tác phẩm kinh điển siêu nhiên thập niên 80.", l: "" }, 3: { d: "Triều đại Nữ hoàng Elizabeth II và những sự kiện định hình nửa sau thế kỷ 20 và hơn thế.", l: "" }, 4: { d: "Thông minh, châm biếm và hơi chết bên trong, Wednesday Addams điều tra chuỗi vụ giết người ở trường khi khám phá năng lực tâm linh mới.", l: "" } },
  id: { 1: { d: "Ketika seorang bocah hilang, kota kecil mengungkap misteri percobaan rahasia, kekuatan gaib menakutkan, dan gadis aneh. Surat cinta untuk klasik gaib era 80-an.", l: "" }, 3: { d: "Pemerintahan Ratu Elizabeth II dan peristiwa yang membentuk paruh kedua abad ke-20 dan seterusnya.", l: "" }, 4: { d: "Cerdas, sarkastik, dan sedikit mati di dalam, Wednesday Addams menyelidiki rangkaian pembunuhan di sekolah sembari menemukan kemampuan psikis barunya.", l: "" } },
  ms: { 1: { d: "Apabila seorang budak lelaki hilang, sebuah pekan kecil mendedahkan misteri eksperimen rahsia, kuasa ghaib menakutkan dan gadis pelik. Surat cinta kepada klasik ghaib era 80-an.", l: "" }, 3: { d: "Pemerintahan Ratu Elizabeth II dan peristiwa yang membentuk separuh kedua abad ke-20 dan seterusnya.", l: "" }, 4: { d: "Pandai, sarkastik dan sedikit mati di dalam, Wednesday Addams menyiasat siri pembunuhan di sekolah sambil menemui keupayaan psikik barunya.", l: "" } },
  hi: { 1: { d: "जब एक युवा लड़का गायब होता है, एक छोटा शहर गुप्त प्रयोगों, भयानक अलौकिक शक्तियों और एक अजीब लड़की से जुड़े रहस्य का खुलासा करता है। 80 के दशक की अलौकिक क्लासिक्स के लिए प्रेम पत्र।", l: "" }, 3: { d: "रानी एलिजाबेथ द्वितीय का शासनकाल और 20वीं सदी के उत्तरार्ध को आकार देने वाली घटनाएं।", l: "" }, 4: { d: "बुद्धिमान, व्यंग्यात्मक और भीतर से थोड़ी मरी हुई, Wednesday Addams अपने नए मानसिक कौशल की खोज करते हुए स्कूल में हत्याओं की श्रृंखला की जांच करती है।", l: "" } },
  sv: { 1: { d: "När en pojke försvinner upptäcker en liten stad ett mysterium med hemliga experiment, skrämmande övernaturliga krafter och en konstig flicka. En kärleksbrev till 80-talets övernaturliga klassiker.", l: "" }, 3: { d: "Drottning Elizabeth II:s regeringstid och händelserna som formade andra hälften av 1900-talet och framåt.", l: "" }, 4: { d: "Smart, sarkastisk och lite död inuti, Wednesday Addams utreder en mordserie på skolan samtidigt som hon upptäcker sina nya psykiska förmågor.", l: "" } },
  da: { 1: { d: "Når en dreng forsvinder, afdækker en lille by et mysterium med hemmelige eksperimenter, skræmmende overnaturlige kræfter og en mærkelig pige. Et kærlighedsbrev til 80'ernes overnaturlige klassikere.", l: "" }, 3: { d: "Dronning Elizabeth II's regeringstid og begivenhederne der formede anden halvdel af det 20. århundrede og fremover.", l: "" }, 4: { d: "Klog, sarkastisk og lidt død indeni, Wednesday Addams undersøger en mordserie på sin skole mens hun opdager sine nye psykiske evner.", l: "" } },
  no: { 1: { d: "Når en ung gutt forsvinner, avdekker en liten by et mysterium med hemmelige eksperimenter, skremmende overnaturlige krefter og en merkelig jente. Et kjærlighetsbrev til 80-tallets overnaturlige klassikere.", l: "" }, 3: { d: "Dronning Elizabeth IIs regjeringstid og hendelsene som formet andre halvdel av det 20. århundre og videre.", l: "" }, 4: { d: "Smart, sarkastisk og litt død inni, Wednesday Addams etterforsker en mordserie på skolen mens hun oppdager sine nye psykiske evner.", l: "" } },
  fi: { 1: { d: "Kun nuori poika katoaa, pieni kaupunki paljastaa salaisia kokeita, pelottavia yliluonnollisia voimia ja outoa tyttöä koskevan mysteerin. Rakkauskirje 80-luvun yliluonnollisille klassikoille.", l: "" }, 3: { d: "Kuningatar Elisabet II:n valtakausi ja 1900-luvun jälkimmäisen puoliskon ja sen jälkeen tapahtumat.", l: "" }, 4: { d: "Älykäs, sarkastinen ja hieman sisältä kuollut Wednesday Addams tutkii murhasarjaa koulussaan löytäessään uusia psyykkisiä kykyjä.", l: "" } },
  cs: { 1: { d: "Když mladý chlapec zmizí, malé město odhalí záhadu zahrnující tajné experimenty, děsivé nadpřirozené síly a podivnou dívku. Milostný dopis nadpřirozeným klasikám 80. let.", l: "" }, 3: { d: "Vláda královny Alžběty II. a události formující druhou polovinu 20. století a dál.", l: "" }, 4: { d: "Chytrá, sarkastická a trochu mrtvá uvnitř, Wednesday Addams vyšetřuje sérii vražd ve škole při objevování svých nových psychických schopností.", l: "" } },
  hu: { 1: { d: "Amikor egy fiatal fiú eltűnik, egy kisváros titkos kísérleteket, rémes természetfeletti erőket és egy furcsa kislányt felfedő rejtelemre bukkan. Szerelmes levél a 80-as évek természetfeletti klasszikusaihoz.", l: "" }, 3: { d: "II. Erzsébet királynő uralkodása és a 20. század második felét formáló események.", l: "" }, 4: { d: "Okos, szarkasztikus és kissé halott belül, Wednesday Addams nyomoz a suliban történt gyilkosságsorozat ügyében, miközben felfedi új pszichikus képességeit.", l: "" } },
  ro: { 1: { d: "Când un băiat dispare, un orășel descoperă un mister cu experimente secrete, forțe supranaturale înfricoșătoare și o fată ciudată. Scrisoare de dragoste clasicei supranaturale din anii 80.", l: "" }, 3: { d: "Domnia reginei Elisabeta a II-a și evenimentele care au modelat a doua jumătate a secolului XX și dincolo.", l: "" }, 4: { d: "Inteligentă, sarkastică și puțin moartă în interior, Wednesday Addams investighează o serie de crime la școală descoperindu-și noile abilități psihice.", l: "" } },
  el: { 1: { d: "Όταν ένα νεαρό αγόρι εξαφανίζεται, μια μικρή πόλη αποκαλύπτει μυστήριο με μυστικά πειράματα, τρομακτικές υπερφυσικές δυνάμεις και ένα περίεργο κοριτσάκι. Ερωτικό γράμμα στα υπερφυσικά κλασικά της δεκαετίας του 80.", l: "" }, 3: { d: "Η βασιλεία της βασίλισσας Ελισάβετ Β' και τα γεγονότα που διαμόρφωσαν το δεύτερο μισό του 20ού αιώνα και πέρα.", l: "" }, 4: { d: "Έξυπνη, σαρκαστική και λίγο νεκρή μέσα, η Wednesday Addams ερευνά σειρά δολοφονιών στο σχολείο ενώ ανακαλύπτει τις νέες ψυχικές της ικανότητες.", l: "" } },
};

// Try user's language first, then fall back to English
const FALLBACK_LANGS = ["en"];

export function getContentDescription(lang, contentId, type, fallback) {
  const typeKey = type === "longDescription" ? "l" : "d";
  for (const l of [lang, ...FALLBACK_LANGS.filter((x) => x !== lang)]) {
    const tr = CONTENT_TRANSLATIONS[l]?.[contentId];
    if (tr?.[typeKey]) return tr[typeKey];
  }
  return fallback || "";
}
